# Generated by Django 3.0.5 on 2020-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200430_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='An empty room...', max_length=500),
        ),
    ]
